export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS';
export const SEARCH_LOADING = 'SEARCH_LOADING';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const ADD_SEARCH_TO_HISTORY = 'ADD_SEARCH_TO_HISTORY';
