export const ADD_SEARCH_RESULTS = 'ADD_SEARCH_RESULTS';
export const SEARCH_RESULTS_LOADING = 'SEARCH_RESULTS_LOADING';
export const SEARCH_RESULTS_FAILED = 'SEARCH_RESULTS_FAILED';
export const UPDATE_SEARCH_INPUT = 'UPDATE_SEARCH_INPUT';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
